### ISSUE TITLE
README 업데이트

### ISSUE THREAD

**Issue by jacob3015** [playdata-july-web/july-spring-fullstack#46]
## 📑 이슈 내용
- Github README를 업데이트합니다.

**Comment by Hans928** [comment]
![tag](https://user-images.githubusercontent.com/91239404/180363894-00bb1578-7706-404f-85d0-0655aecc1587.png)
![title](https://user-images.githubusercontent.com/91239404/180363899-f1b6e810-c717-4d6a-9697-27e2cbd58332.png)
<img width="362" alt="예외" src="https://user-images.githubusercontent.com/91239404/180363905-bcc6225e-10e0-4054-b6ed-208cbd7ee8d8.PNG">
